#include "SimpleForwardShaderFiles.h"

#include <optional>
#include <unordered_map>
#include <vector>

#include "PipelineConfig.h"
#include "ShaderFiles.h"

namespace GraphicsApi::Vulkan
{
namespace
{
const std::unordered_map<GraphicsApi::ShaderProgramType, PipelineConfig> pipelineConfigurations = {
    {GraphicsApi::ShaderProgramType::Loading,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Game/loadingShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Game/loadingShader.frag"}}}},
    {GraphicsApi::ShaderProgramType::Entity,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Entity/Forward/SimpleEntityShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Entity/Forward/SimpleEntityShader.frag"}}}},
    {GraphicsApi::ShaderProgramType::InstancesEntity,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Entity/Forward/InstancesSimpleEntityShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Entity/Forward/SimpleEntityShader.frag"}}}},
    {GraphicsApi::ShaderProgramType::InstancesSimpleForwadEntity,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Entity/Forward/InstancesSimpleEntityShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Entity/Forward/SimpleEntityShader.frag"}}}},
    {GraphicsApi::ShaderProgramType::PreviewEntity,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Entity/PreviewEntity.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Entity/PreviewEntity.frag"}}}},
    {GraphicsApi::ShaderProgramType::DebugObject,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "DebugShaders/debugObjectShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "DebugShaders/debugObjectShader.frag"}}}},
    {GraphicsApi::ShaderProgramType::Grid,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "DebugShaders/gridShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "DebugShaders/gridShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      true,
      true,
      true}},
    {GraphicsApi::ShaderProgramType::Line,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "DebugShaders/lineDebugShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "DebugShaders/lineDebugShader.frag"}},
      Topology::LineList,
      PolygonMode::Line,
      CullMode::None,
      true,
      false,
      false}},
    {GraphicsApi::ShaderProgramType::Grass,
     {{
          {GraphicsApi::ShaderType::VERTEX_SHADER, "Grass/Forward/GrassShader.vert"},
          {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Grass/Forward/GrassShader.frag"},
      },
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None}},
    {GraphicsApi::ShaderProgramType::TreeLeafs,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Tree/LeafShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Tree/Forward/LeafShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None}},
    {GraphicsApi::ShaderProgramType::TreeLeafsCluster,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Tree/LeafClusterShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Tree/Forward/LeafClusterShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None}},
    {GraphicsApi::ShaderProgramType::TreeLeafsClusterCreation,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Tree/LeafClusterCreationShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Tree/LeafClusterCreationShader.frag"}}}},
    {GraphicsApi::ShaderProgramType::Particles,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Particles/Forward/ParticlesShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Particles/Forward/ParticlesShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      true,
      false,
      true}},
    {GraphicsApi::ShaderProgramType::AnimatedParticles,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Particles/Forward/AnimatedParticlesShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Particles/Forward/AnimatedParticlesShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      true,
      false,
      true}},
    {GraphicsApi::ShaderProgramType::Plants,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Particles/Forward/AnimatedParticlesShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Particles/Forward/AnimatedParticlesShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None}},
    {GraphicsApi::ShaderProgramType::Shadows,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Shadows/ShadowVertexShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Shadows/ShadowFragmentShader.frag"}}}},
    {GraphicsApi::ShaderProgramType::InstancesShadows,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Shadows/InstancedShadowVertexShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Shadows/ShadowFragmentShader.frag"}}}},
    {GraphicsApi::ShaderProgramType::SkyBox,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "SkyBox/Forward/SkyboxVertexShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "SkyBox/Forward/SkyboxFragmentShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      true,
      false,
      false}},
    {GraphicsApi::ShaderProgramType::Skydome,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Skydome/Forward/Skydome.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Skydome/Forward/Skydome.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      true,
      false,
      false}},
    {GraphicsApi::ShaderProgramType::SimpleSky,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "PostProcess/Sky/SimpleSky.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "PostProcess/Sky/SimpleSky.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      true,
      false,
      false}},
    {GraphicsApi::ShaderProgramType::Terrain,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Terrain/Tessllation/Forward/TerrainShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Terrain/Tessllation/Forward/TerrainShader.frag"},
       {GraphicsApi::ShaderType::TESS_CONTROL_SHADER, "Terrain/Tessllation/Forward/TerrainShader.cs"},
       {GraphicsApi::ShaderType::TESS_EVALUATION_SHADER, "Terrain/Tessllation/Forward/TerrainShader.es"}},
      Topology::PatchList,
      PolygonMode::Fill,
      CullMode::Back}},
    {GraphicsApi::ShaderProgramType::TerrainMesh,
     PipelineConfig{
         .shaders          = ShadersFiles{{GraphicsApi::ShaderType::VERTEX_SHADER, "Terrain/Mesh/Forward/TerrainShader.vert"},
                                 {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Terrain/Mesh/Forward/TerrainShader.frag"}},
         .topology         = Topology::TriangleStrip,
         .polygonMode      = PolygonMode::Fill,
         .cullMode         = CullMode::Back,
         .depthTestEnable  = true,
         .depthWriteEnable = true,
         .blendEnable      = false,
         .primitiveRestartEnable = false,
         .descriptorSetLayouts   = {},
         .pushConstantSize       = 0}},
    {GraphicsApi::ShaderProgramType::Water,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Water/simpleWater.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Water/simpleWater.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      true,
      false,
      true}},
    {GraphicsApi::ShaderProgramType::Blur,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "PostProcess/Blur/Blur.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "PostProcess/Blur/Blur.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      false,
      false,
      false}},
    {GraphicsApi::ShaderProgramType::ColorFilper,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "PostProcess/ColorFliper/ColorFliper.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "PostProcess/ColorFliper/ColorFliper.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      false,
      false,
      false}},
    {GraphicsApi::ShaderProgramType::Deffered,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Light/LightPassShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Light/LightPassShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      false,
      false,
      false}},
    {GraphicsApi::ShaderProgramType::SSAO,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "PostProcess/SSAO/SSAOShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "PostProcess/SSAO/SSAOShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      false,
      false,
      false}},
    {GraphicsApi::ShaderProgramType::Font,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Font/fontVertex.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Font/fontFragment.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      false,
      false,
      true}},
    {GraphicsApi::ShaderProgramType::Texture,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "Gui/guiVertexShader.vert"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "Gui/guiFragmentShader.frag"}},
      Topology::TriangleList,
      PolygonMode::Fill,
      CullMode::None,
      false,
      false,
      true}},
    {GraphicsApi::ShaderProgramType::DebugNormal,
     {{{GraphicsApi::ShaderType::VERTEX_SHADER, "DebugShaders/NormalShader.vert"},
       {GraphicsApi::ShaderType::GEOMETRY_SHADER, "DebugShaders/NormalShader.geom"},
       {GraphicsApi::ShaderType::FRAGMENT_SHADER, "DebugShaders/NormalShader.frag"}}}}};

}

std::optional<PipelineConfig> GetSimpleForwardShaderFiles(GraphicsApi::ShaderProgramType shaderType)
{
    auto configIter = pipelineConfigurations.find(shaderType);
    if (configIter != pipelineConfigurations.end())
    {
        return configIter->second;
    }

    return std::nullopt;
}

}  // namespace GraphicsApi::Vulkan
