#pragma once

namespace GraphicsApi
{
enum class ShaderProgramType
{
    Entity,
    InstancesEntity,
    PreviewEntity,
    SimpleForwadEntity,
    InstancesSimpleForwadEntity,
    DebugObject,
    Grass,
    Particles,
    AnimatedParticles,
    Plants,
    Shadows,
    InstancesShadows,
    ForwardSkyBox,
    SkyBox,
    Skydome,
    Sky,
    SimpleSky,
    Terrain,
    TerrainMesh,
    SimpleForwardTerrainMesh,
    TreeLeafs,
    TreeLeafsShdaows,
    TreeLeafsShdaowsBilboards,
    TreeLeafsCluster,
    TreeLeafsClusterCreation,
    LightShaftOclusion,
    LightShaftBlure,
    Water,
    SSAO,
    SsaoBlure,
    ColorFilper,
    Blur,
    Deffered,
    Loading,
    Font,
    Texture,
    Grid,
    Line,
    DebugNormal,
    Fxaa,
    Sobel,
    Outline,
    ACESFilmicToneMapping
};
}  // namespace GraphicsApi
