set(LibNoiseSources
../Tools/common/libnoise/src/model/cylinder.cpp
../Tools/common/libnoise/src/model/line.cpp
../Tools/common/libnoise/src/model/plane.cpp
../Tools/common/libnoise/src/model/sphere.cpp
../Tools/common/libnoise/src/module/clamp.cpp
../Tools/common/libnoise/src/module/spheres.cpp
../Tools/common/libnoise/src/module/billow.cpp
../Tools/common/libnoise/src/module/select.cpp
../Tools/common/libnoise/src/module/translatepoint.cpp
../Tools/common/libnoise/src/module/cache.cpp
../Tools/common/libnoise/src/module/blend.cpp
../Tools/common/libnoise/src/module/terrace.cpp
../Tools/common/libnoise/src/module/scalepoint.cpp
../Tools/common/libnoise/src/module/ridgedmulti.cpp
../Tools/common/libnoise/src/module/voronoi.cpp
../Tools/common/libnoise/src/module/min.cpp
../Tools/common/libnoise/src/module/scalebias.cpp
../Tools/common/libnoise/src/module/cylinders.cpp
../Tools/common/libnoise/src/module/rotatepoint.cpp
../Tools/common/libnoise/src/module/multiply.cpp
../Tools/common/libnoise/src/module/turbulence.cpp
../Tools/common/libnoise/src/module/modulebase.cpp
../Tools/common/libnoise/src/module/invert.cpp
../Tools/common/libnoise/src/module/curve.cpp
../Tools/common/libnoise/src/module/const.cpp
../Tools/common/libnoise/src/module/checkerboard.cpp
../Tools/common/libnoise/src/module/perlin.cpp
../Tools/common/libnoise/src/module/add.cpp
../Tools/common/libnoise/src/module/exponent.cpp
../Tools/common/libnoise/src/module/max.cpp
../Tools/common/libnoise/src/module/power.cpp
../Tools/common/libnoise/src/module/abs.cpp
../Tools/common/libnoise/src/module/displace.cpp
../Tools/common/libnoise/src/latlon.cpp
../Tools/common/libnoise/src/noisegen.cpp
)
