set(AvatarSources
../../Sources/Avatar/StartGame.cpp
../../Sources/Avatar/Scene/SceneFactory.cpp
../../Sources/Avatar/Scene/Scenes/PauseMenuTheme.cpp
../../Sources/Avatar/Scene/Scenes/MainMenu.cpp
../../Sources/Avatar/Scene/Scenes/SouthPole.cpp
../../Sources/Avatar/Scene/Scenes/GreenIsland.cpp
../../Sources/Avatar/Game/PauseMenu.cpp
../../Sources/Avatar/main.cpp
)
