set(AvatarSources
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Scene/SceneFactory.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Scene/Scenes/MainMenu.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Scene/Scenes/PauseMenuTheme.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Scene/Scenes/SouthPole.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Scene/Scenes/GreenIsland.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Scene/Scenes/Kingdom.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/main.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/Inventory/Boots.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/Inventory/Item.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/PauseMenu.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/StartGame.cpp
)
