set(CommonSources
../../Sources/Common/Controllers/CharacterController/Character.cpp
../../Sources/Common/Controllers/CharacterController/NetworkActionsConverter.cpp
../../Sources/Common/Controllers/ControllersFactory.cpp
../../Sources/Common/MessageHandling/Dispatcher.cpp
../../Sources/Common/Messages/IMessage.cpp
../../Sources/Common/Messages/MessageTypes.cpp
../../Sources/Common/Transform.cpp
)
