set(DirectXApiSources
../../Sources/DirectXApi/DirectXTools.cpp
../../Sources/DirectXApi/DxFrameBuffer.cpp
../../Sources/DirectXApi/Shaders/DxForwardShaderFiles.cpp
../../Sources/DirectXApi/DirectXApi.cpp
../../Sources/DirectXApi/Object.cpp
../../Sources/DirectXApi/WinApi/XInput/XInputManager.cpp
../../Sources/DirectXApi/WinApi/XInput/WinApiKeyConverter.cpp
../../Sources/DirectXApi/WinApi/WinApi.cpp
)
