set(GameEngineTestsSources
../../Sources/GameEngineTests/Tests/MT/GUI/GuiTextTests.cpp
../../Sources/GameEngineTests/Tests/Network/ServerCreatorTests.cpp
../../Sources/GameEngineTests/Tests/UT/Resources/ColladaLoaderTests.cpp
../../Sources/GameEngineTests/Tests/UT/Resources/TextureLoader.cpp
../../Sources/GameEngineTests/Tests/UT/Renderers/EntityRendererTest.cpp
../../Sources/GameEngineTests/Tests/UT/Scene/Scene.cpp
../../Sources/GameEngineTests/Tests/UT/Components/AnimatorTests.cpp
../../Sources/GameEngineTests/Tests/UT/Components/Particles/ParticleEffectComponentTests.cpp
../../Sources/GameEngineTests/Tests/UT/Components/BaseComponent.cpp
../../Sources/GameEngineTests/Tests/Mocks/Api/GraphicsApiMock.cpp
../../Sources/GameEngineTests/main.cpp
)
