set(GameEngineTestsSources
../../Sources/GameEngineTests/main.cpp
../../Sources/GameEngineTests/Tests/Mocks/Api/GraphicsApiMock.cpp
../../Sources/GameEngineTests/Tests/MT/GUI/GuiTextTests.cpp
../../Sources/GameEngineTests/Tests/UT/Camera/CameraFrustrumTests.cpp
../../Sources/GameEngineTests/Tests/UT/Components/AnimatorTests.cpp
../../Sources/GameEngineTests/Tests/UT/Components/BaseComponent.cpp
../../Sources/GameEngineTests/Tests/UT/Components/Particles/ParticleEffectComponentTests.cpp
../../Sources/GameEngineTests/Tests/UT/Renderers/EntityRendererTest.cpp
../../Sources/GameEngineTests/Tests/UT/Renderers/Gui/GuiElementTests.cpp
../../Sources/GameEngineTests/Tests/UT/Renderers/Gui/HorizontalLayoutTests.cpp
../../Sources/GameEngineTests/Tests/UT/Renderers/Gui/VerticalLayoutTests.cpp
../../Sources/GameEngineTests/Tests/UT/Renderers/TerrainNormalCalulation.cpp
../../Sources/GameEngineTests/Tests/UT/Resources/AssimpLoaderTests.cpp
../../Sources/GameEngineTests/Tests/UT/Resources/ColladaLoaderTests.cpp
../../Sources/GameEngineTests/Tests/UT/Resources/FbxLoader.cpp
../../Sources/GameEngineTests/Tests/UT/Resources/TextureLoader.cpp
../../Sources/GameEngineTests/Tests/UT/Resources/WaveFrontObjLoaderTests.cpp
../../Sources/GameEngineTests/Tests/UT/Scene/Scene.cpp
../../Sources/GameEngineTests/Tests/UT/TerrainHeightGetterTests.cpp
../../Sources/GameEngineTests/Tests/UT/TerrainToolsTests.cpp
../../Sources/GameEngineTests/Tests/UT/TerrainTransitionTests.cpp
../../Sources/GameEngineTests/Tests/UT/Utils/utilsTests.cpp
)
