set(GwintSources
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Gwint/GameScene.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Gwint/States/State.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Gwint/Gwint.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Gwint/Cards/GameCards.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Gwint/Cards/CardReader.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Gwint/main.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Gwint/Network/NetworkUtils.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Gwint/Network/SDLClientGetway.cpp
)
