set(GwintSources
../../Sources/Gwint/main.cpp
../../Sources/Gwint/States/State.cpp
../../Sources/Gwint/Network/NetworkUtils.cpp
../../Sources/Gwint/Network/SDLClientGetway.cpp
../../Sources/Gwint/Cards/CardReader.cpp
../../Sources/Gwint/Cards/GameCards.cpp
../../Sources/Gwint/GameScene.cpp
../../Sources/Gwint/Gwint.cpp
)
