set(OpenGLApiSources
../../Sources/OpenGLApi/IdPool.cpp
../../Sources/OpenGLApi/SDL2/SdlKeyConverter.cpp
../../Sources/OpenGLApi/SDL2/InputSDL.cpp
../../Sources/OpenGLApi/SDL2/SDLOpenGL.cpp
../../Sources/OpenGLApi/OpenGLUtils.cpp
../../Sources/OpenGLApi/SimpleModels/Quad.cpp
../../Sources/OpenGLApi/Shaders/SimpleForwardShaderFiles.cpp
../../Sources/OpenGLApi/Shaders/FullDefferedShaderFiles.cpp
../../Sources/OpenGLApi/Shaders/ShaderManager.cpp
../../Sources/OpenGLApi/Shaders/SimpleDeprecetedShaders.cpp
../../Sources/OpenGLApi/OpenGLApi.cpp
../../Sources/OpenGLApi/Font.cpp
)
