set(RpgGameServerSources
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Hero/HeroFactory.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Hero/BaseHero.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Hero/Classes/Knight.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Context.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Database/LocalDatabase.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Database/DatabaseWrapperMock.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Scenarios/CharacterSelect/CharacterSelect.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/User.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Manager.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/GameServer.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/CharacterController/CharacterControllerHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/GetCharacters/GetCharactersHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/GetCharactersData/GetCharactersDataHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/Distribute/DistributeHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/SelectCharacter/SelectCharacterHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/ControllerCreator.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Map.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/main.cpp
)
