set(RpgGameServerSources
../../Sources/RpgGameServer/GameServer/Context.cpp
../../Sources/RpgGameServer/GameServer/ControllerCreator.cpp
../../Sources/RpgGameServer/GameServer/Database/DatabaseWrapperMock.cpp
../../Sources/RpgGameServer/GameServer/Database/LocalDatabase.cpp
../../Sources/RpgGameServer/GameServer/GameServer.cpp
../../Sources/RpgGameServer/GameServer/Handlers/CharacterController/CharacterControllerHandler.cpp
../../Sources/RpgGameServer/GameServer/Handlers/Distribute/DistributeHandler.cpp
../../Sources/RpgGameServer/GameServer/Handlers/GetCharacters/GetCharactersHandler.cpp
../../Sources/RpgGameServer/GameServer/Handlers/GetCharactersData/GetCharactersDataHandler.cpp
../../Sources/RpgGameServer/GameServer/Handlers/SelectCharacter/SelectCharacterHandler.cpp
../../Sources/RpgGameServer/GameServer/Hero/BaseHero.cpp
../../Sources/RpgGameServer/GameServer/Hero/Classes/Knight.cpp
../../Sources/RpgGameServer/GameServer/Hero/HeroFactory.cpp
../../Sources/RpgGameServer/GameServer/Manager.cpp
../../Sources/RpgGameServer/GameServer/Map.cpp
../../Sources/RpgGameServer/GameServer/Scenarios/CharacterSelect/CharacterSelect.cpp
../../Sources/RpgGameServer/GameServer/User.cpp
../../Sources/RpgGameServer/main.cpp
)
