set(TestGameSources
../../Sources/TestGame/MRpg/PlayerMock.cpp
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/SelectCharacterScene.cpp
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/GetCharacterState.cpp
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/WaitForConfirmationState.cpp
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/SelectingCharacterState.cpp
../../Sources/TestGame/MRpg/Scenes/Login/Login.cpp
../../Sources/TestGame/MRpg/Scenes/ScenesFactory.cpp
../../Sources/TestGame/MRpg/Scenes/MainScene/MainRpgScene.cpp
../../Sources/TestGame/MRpg/Scenes/MRpgScene.cpp
../../Sources/TestGame/MRpg/Handlers/SelectCharacter/SelectCharacterHandler.cpp
../../Sources/TestGame/MRpg/Handlers/GetCharacter/GetCharactersHandler.cpp
../../Sources/TestGame/MRpg/Handlers/Transform/TransformHandler.cpp
../../Sources/TestGame/MRpg/Handlers/DisconnectCharacter/DisconnectHandler.cpp
../../Sources/TestGame/MRpg/Handlers/GetCharacterData/GetCharacterDataHandler.cpp
../../Sources/TestGame/MRpg/Characters/ModelsCreator.cpp
../../Sources/TestGame/MRpg/Characters/NetworkCharacter.cpp
../../Sources/TestGame/MRpg/Characters/PlayerController.cpp
../../Sources/TestGame/MRpg/Characters/NetworkCharacterManger.cpp
../../Sources/TestGame/MRpg/mrpg_main.cpp
../../Sources/TestGame/GuiEdytorScene.cpp
../../Sources/TestGame/Physics/PhyscisTestScene.cpp
../../Sources/TestGame/Physics/Scenes/PhysicsSceneFactory.cpp
../../Sources/TestGame/Physics/Scenes/PhysicsScene.cpp
../../Sources/TestGame/main.cpp
../../Sources/TestGame/Single/SingleStart.cpp
../../Sources/TestGame/Single/Scene/MainScene.cpp
../../Sources/TestGame/Single/Scene/TestSceneFactory.cpp
../../Sources/TestGame/Single/PlayerInputController.cpp
)
