set(TestGameSources
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Physics/Scenes/PhysicsSceneFactory.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Physics/Scenes/PhysicsScene.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Physics/PhyscisTestScene.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Characters/NetworkCharacterManger.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Characters/ModelsCreator.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Characters/NetworkCharacter.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Characters/PlayerController.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/MainScene/MainRpgScene.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/SelectCharacterScene.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/WaitForConfirmationState.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/SelectingCharacterState.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/GetCharacterState.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/Login/Login.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/ScenesFactory.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/MRpgScene.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/GetCharacter/GetCharactersHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/GetCharacterData/GetCharacterDataHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/SelectCharacter/SelectCharacterHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/DisconnectCharacter/DisconnectHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/Transform/TransformHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/PlayerMock.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/mrpg_main.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/GuiEdytorScene.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Single/PlayerInputController.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Single/SingleStart.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Single/Scene/TestSceneFactory.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Single/Scene/MainScene.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/main.cpp
)
