set(TestGameSources
../../Sources/TestGame/GuiEdytorScene.cpp
../../Sources/TestGame/main.cpp
../../Sources/TestGame/MainScene.cpp
../../Sources/TestGame/MRpg/Characters/NetworkCharacter.cpp
../../Sources/TestGame/MRpg/Characters/PlayerController.cpp
../../Sources/TestGame/MRpg/mrpg_main.cpp
../../Sources/TestGame/MRpg/Scenes/Login.cpp
../../Sources/TestGame/MRpg/Scenes/MainScene/MainRpgScene.cpp
../../Sources/TestGame/MRpg/Scenes/ScenesFactory.cpp
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/SelectCharacterScene.cpp
../../Sources/TestGame/Player.cpp
)
