set(UtilsSources
../../Sources/Utils/Logger/Log.cpp
../../Sources/Utils/Utils.cpp
../../Sources/Utils/XML/ParseMethods.cpp
../../Sources/Utils/XML/SceneReader.cpp
../../Sources/Utils/XML/SerializedMethods.cpp
../../Sources/Utils/XML/XMLUtils.cpp
../../Sources/Utils/OpenGL/OpenGLUtils.cpp
../../Sources/Utils/OpenGL/VaoEnableController.cpp
../../Sources/Utils/Types.cpp
../../Sources/Utils/EngineUitls.cpp
../../Sources/Utils/Time/TimeMeasurer.cpp
../../Sources/Utils/GLM/GLMUtils.cpp
../../Sources/Utils/ThreadSync.cpp
../../Sources/Utils/ParseUtils.cpp
)
