set(UtilsNetworkSources
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/NetworkCreator.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/ServerCreator.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/Reciever.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/Messages/XmlConverterUtils.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/Messages/TextMessage.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/Messages/MessageTypes.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/Messages/XmlConnectionMessageConverter.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/Messages/BinaryConnectionMessageConverter.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/ConnectionManager.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/Gateway.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/Sender.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/MessageFormat.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/SDLNetWrapper.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/ClientCreator.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/NetworkUtils.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/UtilsNetwork/IMessage.cpp
)
