set(UtilsNetworkSources
../../Sources/UtilsNetwork/SDLNetWrapper.cpp
../../Sources/UtilsNetwork/Messages/IMessage.cpp
../../Sources/UtilsNetwork/Messages/MessageTypes.cpp
../../Sources/UtilsNetwork/ConnectionManager.cpp
../../Sources/UtilsNetwork/Gateway.cpp
../../Sources/UtilsNetwork/NetworkUtils.cpp
../../Sources/UtilsNetwork/Reciever.cpp
../../Sources/UtilsNetwork/BoxesGateway.cpp
../../Sources/UtilsNetwork/ClientCreator.cpp
../../Sources/UtilsNetwork/ServerCreator.cpp
../../Sources/UtilsNetwork/NetworkCreator.cpp
../../Sources/UtilsNetwork/Sender.cpp
)
