set(UtilsSources
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Worker.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/FileSystem/FileSystemUtils.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Beizer.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/MeasurementHandler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/IdPool.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/GLM/GLMUtils.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Image/Image.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Image/ImageUtils.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Image/ImageFilters.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/md5.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Rotation.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/XML/ParseMethods.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/XML/XMLUtils.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/XML/XmlWriter.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/XML/SceneReader.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/XML/XmlReader.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/XML/SerializedMethods.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/ThreadSync.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/ParseUtils.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Time/TimerService.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Time/Timer.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Time/TimeMeasurer.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Types.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Utils.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/Logger/Log.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/EngineUitls.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/ThreadSubscriber.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Utils/TreeNode.cpp
)
