set(VulkanApiSources
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/VulkanApi/InputSDL.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/VulkanApi/SimpleForwardShaderFiles.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/VulkanApi/SdlKeyConverter.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/VulkanApi/VulkanApi.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/VulkanApi/VulkanContext.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/VulkanApi/VulkanShaderCompiler.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/VulkanApi/SdlVulkanApi.cpp
)
