set(WindowAppCreatorSources
../../Sources/WindowAppCreator/Items/Item.cpp
../../Sources/WindowAppCreator/Items/Window.cpp
../../Sources/WindowAppCreator/Items/ItemsGroup.cpp
../../Sources/WindowAppCreator/Items/windows/Button/Win32_Button.cpp
../../Sources/WindowAppCreator/Items/windows/Window/Win32_Window.cpp
../../Sources/WindowAppCreator/Items/windows/WindowsItemsBuilder.cpp
../../Sources/WindowAppCreator/main.cpp
../../Sources/WindowAppCreator/WindowAppCreator.cpp
)
