set(WindowAppCreatorSources
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/Item.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/windows/WindowsItemsBuilder.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/windows/Button/Win32_Button.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/windows/Window/Win32_Window.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/Window.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/ItemsGroup.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/WindowAppCreator.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/main.cpp
)
