set(WxEditorSources
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxOpenGLApiWrapper.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPickerPopup.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Theme.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ProjectPanel.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/DisableHelper.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxInputManager.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxWindowApi.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/OptionsFrame.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxEditorSceneDll.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/MainFrame.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TransformPanel.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/main.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/GLCanvas.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/App.cpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/SceneTreeCtrl.cpp
)
