set(AvatarIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Scene/SceneFactory.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/StartGame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/PauseMenuComponent.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/PauseMenuTheme.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/PauseMenu.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/Inventory/CharacterStats.hpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/Inventory/Boots.hpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/Inventory/Damage.hpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/Inventory/Item.hpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/Inventory/MagicProperty.hpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/Inventory/BaseStats.hpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Avatar/Game/Character.hpp
)
