set(CommonIncludes
../../Sources/Common/MessageHandling/Dispatcher.h
../../Sources/Common/MessageHandling/AbstractHandler.h
../../Sources/Common/Hero/HeroClassesTypes.h
../../Sources/Common/Hero/Stats.h
../../Sources/Common/Messages/TransformMessages/TransformMsgResp.h
../../Sources/Common/Messages/TransformMessages/TransformMsgReq.h
../../Sources/Common/Messages/TransformMessages/TransformMessageTypes.h
../../Sources/Common/Messages/XmlMessageConverter.h
../../Sources/Common/Messages/BinaryMessageConverter.h
../../Sources/Common/Messages/GetCharacters/CharacterInfo.h
../../Sources/Common/Messages/GetCharacters/GetCharactersMsgResp.h
../../Sources/Common/Messages/GetCharacters/GetCharactersMsgReq.h
../../Sources/Common/Messages/MessageTypes.h
../../Sources/Common/Messages/GetCharacterData/GetCharacterDataMsgResp.h
../../Sources/Common/Messages/GetCharacterData/GetCharacterDataMsgReq.h
../../Sources/Common/Messages/GetCharacterData/GetCharactersDataMsgReq.h
../../Sources/Common/Messages/MessageStatus.h
../../Sources/Common/Messages/SelectCharacter/SelectCharacterMsgResp.h
../../Sources/Common/Messages/SelectCharacter/SelectCharacterMsgReq.h
../../Sources/Common/Messages/CreateCharacter/CreateCharacterMsgResp.h
../../Sources/Common/Messages/CreateCharacter/CreateCharacterMsgReq.h
../../Sources/Common/Messages/RemoveCharacter/DisconnectCharacterMsg.h
../../Sources/Common/Controllers/ControllersTypes.h
../../Sources/Common/Controllers/CharacterController/NetworkActionsConverter.h
../../Sources/Common/Controllers/CharacterController/CharacterActions.h
../../Sources/Common/Controllers/CharacterController/Character.h
../../Sources/Common/Controllers/IController.h
../../Sources/Common/Controllers/ControllersFactory.h
../../Sources/Common/Transform.h
)
