set(CommonIncludes
../../Sources/Common/Controllers/CharacterController/Character.h
../../Sources/Common/Controllers/CharacterController/CharacterActions.h
../../Sources/Common/Controllers/ControllersFactory.h
../../Sources/Common/Controllers/ControllersTypes.h
../../Sources/Common/Controllers/IController.h
../../Sources/Common/Hero/HeroClassesTypes.h
../../Sources/Common/Hero/Stats.h
../../Sources/Common/Transform.h
)
