set(DirectXApiIncludes
../../Sources/DirectXApi/DirectXTools.h
../../Sources/DirectXApi/WinApi/WinApi.h
../../Sources/DirectXApi/WinApi/XInput/XInputManager.h
../../Sources/DirectXApi/WinApi/XInput/WinApiKeyConverter.h
../../Sources/DirectXApi/Object.h
../../Sources/DirectXApi/DxShader.h
../../Sources/DirectXApi/Buffer.h
../../Sources/DirectXApi/DxFrameBuffer.h
../../Sources/DirectXApi/DirectXApi.h
../../Sources/DirectXApi/ViewPort.h
../../Sources/DirectXApi/ShaderManager.h
../../Sources/DirectXApi/Vertex.h
../../Sources/DirectXApi/Shaders/DxForwardShaderFiles.h
../../Sources/DirectXApi/DirectXContext.h
../../Sources/DirectXApi/Vao.h
)
