set(GameEngineIncludes
../../Sources/GameEngine/Animations/AnimationClip.h
../../Sources/GameEngine/Animations/AnimationUtils.h
../../Sources/GameEngine/Animations/Joint.h
../../Sources/GameEngine/Animations/JointTransform.h
../../Sources/GameEngine/Animations/KeyFrame.h
../../Sources/GameEngine/Api/Dummy/DummyGraphicsApi.h
../../Sources/GameEngine/Api/Dummy/DummyInputManager.h
../../Sources/GameEngine/Api/Dummy/DummyWindowApi.h
../../Sources/GameEngine/Camera/Camera.h
../../Sources/GameEngine/Camera/Camera2D.h
../../Sources/GameEngine/Camera/FirstPersonCamera.h
../../Sources/GameEngine/Camera/Frustrum.h
../../Sources/GameEngine/Camera/ICamera.h
../../Sources/GameEngine/Camera/Plane.h
../../Sources/GameEngine/Camera/ThridPersonCamera.h
../../Sources/GameEngine/Components/Animation/Animator.h
../../Sources/GameEngine/Components/BaseComponent.h
../../Sources/GameEngine/Components/ComponentContext.h
../../Sources/GameEngine/Components/ComponentController.h
../../Sources/GameEngine/Components/ComponentFactory.h
../../Sources/GameEngine/Components/ComponentsTypes.h
../../Sources/GameEngine/Components/IComponent.h
../../Sources/GameEngine/Components/IComponentFactory.h
../../Sources/GameEngine/Components/Input/CharacterControllerInput.h
../../Sources/GameEngine/Components/Physics/BoxShape.h
../../Sources/GameEngine/Components/Physics/CollisionShape.h
../../Sources/GameEngine/Components/Physics/DebugDrawner.h
../../Sources/GameEngine/Components/Physics/MeshShape.h
../../Sources/GameEngine/Components/Physics/Rigidbody.h
../../Sources/GameEngine/Components/Physics/SphereShape.h
../../Sources/GameEngine/Components/Physics/Terrain/TerrainHeightGetter.h
../../Sources/GameEngine/Components/Physics/Terrain/TerrainShape.h
../../Sources/GameEngine/Components/Renderer/Grass/GrassComponent.h
../../Sources/GameEngine/Components/Renderer/Particles/ParticleEffectComponent.h
../../Sources/GameEngine/Components/Renderer/SkyBox/SkyBoxComponent.h
../../Sources/GameEngine/Components/Renderer/Skydome/SkydomeComponent.h
../../Sources/GameEngine/Components/Renderer/Terrain/TerrainConfiguration.h
../../Sources/GameEngine/Components/Renderer/Terrain/TerrainDef.h
../../Sources/GameEngine/Components/Renderer/Terrain/TerrainMeshRendererComponent.h
../../Sources/GameEngine/Components/Renderer/Terrain/TerrainNode.h
../../Sources/GameEngine/Components/Renderer/Terrain/TerrainQuadTree.h
../../Sources/GameEngine/Components/Renderer/Terrain/TerrainRendererComponent.h
../../Sources/GameEngine/Components/Renderer/Terrain/TerrainTexturesTypes.h
../../Sources/GameEngine/Components/Renderer/Trees/TreeRendererComponent.h
../../Sources/GameEngine/Engine/AplicationContext.h
../../Sources/GameEngine/Engine/Configuration.h
../../Sources/GameEngine/Engine/ConfigurationReader.h
../../Sources/GameEngine/Engine/ConfigurationWriter.h
../../Sources/GameEngine/Engine/Engine.h
../../Sources/GameEngine/Engine/EngineDef.h
../../Sources/GameEngine/Engine/EngineEvent.h
../../Sources/GameEngine/Engine/EngineMeasurement.h
../../Sources/GameEngine/Engine/IntroRenderer.h
../../Sources/GameEngine/Engine/LoD.h
../../Sources/GameEngine/Lights/Light.h
../../Sources/GameEngine/Lights/LightTypes.h
../../Sources/GameEngine/Objects/GameObject.h
../../Sources/GameEngine/Objects/Particle.h
../../Sources/GameEngine/Physics/Bach/BachPhysicsAdapter.h
../../Sources/GameEngine/Physics/BaseCollider.h
../../Sources/GameEngine/Physics/Bullet/BulletAdapter.h
../../Sources/GameEngine/Physics/Bullet/Converter.h
../../Sources/GameEngine/Physics/Bullet/DebugDrawer.h
../../Sources/GameEngine/Physics/IPhysicsApi.h
../../Sources/GameEngine/Physics/PhysicsScene.h
../../Sources/GameEngine/Physics/Rigidbody.h
../../Sources/GameEngine/Physics/ShapeType.h
../../Sources/GameEngine/Renderers/BaseRenderer.h
../../Sources/GameEngine/Renderers/BufferDataUpdater.h
../../Sources/GameEngine/Renderers/DebugRenderer.h
../../Sources/GameEngine/Renderers/DefferedRenderer.h
../../Sources/GameEngine/Renderers/Framebuffer/DeferedFrameBuffer/DeferedFrameBuffer.h
../../Sources/GameEngine/Renderers/Framebuffer/FrameBuffer.h
../../Sources/GameEngine/Renderers/Framebuffer/IFrameBuffer.h
../../Sources/GameEngine/Renderers/Framebuffer/Postprocessing/PostproccesFrameBuffer.h
../../Sources/GameEngine/Renderers/GUI/GuiContext.h
../../Sources/GameEngine/Renderers/GUI/GuiElement.h
../../Sources/GameEngine/Renderers/GUI/GuiRenderer.h
../../Sources/GameEngine/Renderers/GUI/IGuiElement.h
../../Sources/GameEngine/Renderers/GUI/Rect.h
../../Sources/GameEngine/Renderers/GUI/Text/FontShader.h
../../Sources/GameEngine/Renderers/GUI/Text/FontShaderUniforms.h
../../Sources/GameEngine/Renderers/GUI/Text/GuiText.h
../../Sources/GameEngine/Renderers/GUI/Text/GuiTextElement.h
../../Sources/GameEngine/Renderers/GUI/Texutre/GuiTextureElement.h
../../Sources/GameEngine/Renderers/GUI/Texutre/GuiTextureShader.h
../../Sources/GameEngine/Renderers/GUI/Texutre/GuiTextureShaderUniforms.h
../../Sources/GameEngine/Renderers/IRenderer.h
../../Sources/GameEngine/Renderers/LodingScreenRenderer.h
../../Sources/GameEngine/Renderers/Objects/Entity/EntityRenderer.h
../../Sources/GameEngine/Renderers/Objects/Entity/EntityRendererDef.h
../../Sources/GameEngine/Renderers/Objects/Entity/Shaders/DefferedEntityShader.h
../../Sources/GameEngine/Renderers/Objects/Entity/Shaders/EntityShader.h
../../Sources/GameEngine/Renderers/Objects/Entity/Shaders/EntityShaderUniforms.h
../../Sources/GameEngine/Renderers/Objects/Grass/GrassRenderer.h
../../Sources/GameEngine/Renderers/Objects/Grass/Shaders/GrassShader.h
../../Sources/GameEngine/Renderers/Objects/Grass/Shaders/GrassShaderUniforms.h
../../Sources/GameEngine/Renderers/Objects/Particles/ParticlesRenderer.h
../../Sources/GameEngine/Renderers/Objects/Particles/Shaders/AnimatedParticlesShader.h
../../Sources/GameEngine/Renderers/Objects/Particles/Shaders/ParticlesShader.h
../../Sources/GameEngine/Renderers/Objects/Particles/Shaders/ParticlesShadersUniforms.h
../../Sources/GameEngine/Renderers/Objects/Plants/PlantsRenderer.h
../../Sources/GameEngine/Renderers/Objects/Plants/Shaders/PlantsShader.h
../../Sources/GameEngine/Renderers/Objects/Shadows/Shaders/ShadowShader.h
../../Sources/GameEngine/Renderers/Objects/Shadows/Shaders/ShadowShaderUniforms.h
../../Sources/GameEngine/Renderers/Objects/Shadows/ShadowBox.h
../../Sources/GameEngine/Renderers/Objects/Shadows/ShadowFrameBuffer.h
../../Sources/GameEngine/Renderers/Objects/SkyBox/Shaders/SkyBoxShader.h
../../Sources/GameEngine/Renderers/Objects/SkyBox/Shaders/SkyBoxShaderUniforms.h
../../Sources/GameEngine/Renderers/Objects/SkyBox/SkyBoxRenderer.h
../../Sources/GameEngine/Renderers/Objects/Skydome/Shaders/SkydomeShader.h
../../Sources/GameEngine/Renderers/Objects/Skydome/SkydomeRenderer.h
../../Sources/GameEngine/Renderers/Objects/Terrain/Mesh/Shaders/TerrainMeshShader.h
../../Sources/GameEngine/Renderers/Objects/Terrain/Mesh/Shaders/TerrainMeshShaderUniforms.h
../../Sources/GameEngine/Renderers/Objects/Terrain/Mesh/TerrainMeshRenderer.h
../../Sources/GameEngine/Renderers/Objects/Terrain/Shaders/TerrainNormalMapShader.h
../../Sources/GameEngine/Renderers/Objects/Terrain/Shaders/TerrainNormalMapShaderUniforms.h
../../Sources/GameEngine/Renderers/Objects/Terrain/Shaders/TerrainShader.h
../../Sources/GameEngine/Renderers/Objects/Terrain/Shaders/TerrainShaderUniforms.h
../../Sources/GameEngine/Renderers/Objects/Terrain/TerrainNormalMapRenderer.h
../../Sources/GameEngine/Renderers/Objects/Terrain/TerrainRenderer.h
../../Sources/GameEngine/Renderers/Objects/Tree/Shaders/TreeShader.h
../../Sources/GameEngine/Renderers/Objects/Tree/Shaders/TreeShaderUniforms.h
../../Sources/GameEngine/Renderers/Objects/Tree/TreeRenderer.h
../../Sources/GameEngine/Renderers/Objects/Water/Shaders/WaterShader.h
../../Sources/GameEngine/Renderers/Objects/Water/WaterRenderer.h
../../Sources/GameEngine/Renderers/Postproccesing/Blur/Blur.h
../../Sources/GameEngine/Renderers/Postproccesing/Blur/Shaders/BlurShader.h
../../Sources/GameEngine/Renderers/Postproccesing/Blur/Shaders/BlurShaderUniforms.h
../../Sources/GameEngine/Renderers/Postproccesing/ColorFliper/ColorFliper.h
../../Sources/GameEngine/Renderers/Postproccesing/ColorFliper/Shaders/ColorFliperShader.h
../../Sources/GameEngine/Renderers/Postproccesing/ColorFliper/Shaders/ColorFliperUniformLocation.h
../../Sources/GameEngine/Renderers/Postproccesing/DefferedLighting/DefferedLighting.h
../../Sources/GameEngine/Renderers/Postproccesing/DefferedLighting/Shaders/DefferedShader.h
../../Sources/GameEngine/Renderers/Postproccesing/DefferedLighting/Shaders/DefferedShaderUniforms.h
../../Sources/GameEngine/Renderers/Postproccesing/IPostprocessingRenderersFactory.h
../../Sources/GameEngine/Renderers/Postproccesing/PostprocessingRenderer.h
../../Sources/GameEngine/Renderers/Postproccesing/PostprocessingRenderersFactory.h
../../Sources/GameEngine/Renderers/Postproccesing/PostprocessingRenderersManager.h
../../Sources/GameEngine/Renderers/Postproccesing/PostprocessingRendererTypes.h
../../Sources/GameEngine/Renderers/Postproccesing/SSAO/Shaders/SSAOShader.h
../../Sources/GameEngine/Renderers/Postproccesing/SSAO/Shaders/SSAOShaderUniforms.h
../../Sources/GameEngine/Renderers/Postproccesing/SSAO/SSAO.h
../../Sources/GameEngine/Renderers/Projection.h
../../Sources/GameEngine/Renderers/RendererContext.h
../../Sources/GameEngine/Renderers/RendererFunctionType.h
../../Sources/GameEngine/Renderers/RenderersManager.h
../../Sources/GameEngine/Resources/BufferObject.h
../../Sources/GameEngine/Resources/GpuObject.h
../../Sources/GameEngine/Resources/GpuResourceLoader.h
../../Sources/GameEngine/Resources/IGpuObject.h
../../Sources/GameEngine/Resources/IGpuResourceLoader.h
../../Sources/GameEngine/Resources/ITextureLoader.h
../../Sources/GameEngine/Resources/Models/Assimp/AssimpModel.h
../../Sources/GameEngine/Resources/Models/Bone.h
../../Sources/GameEngine/Resources/Models/BoundingBox.h
../../Sources/GameEngine/Resources/Models/Material.h
../../Sources/GameEngine/Resources/Models/Mesh.h
../../Sources/GameEngine/Resources/Models/Model.h
../../Sources/GameEngine/Resources/Models/ModelFactory.h
../../Sources/GameEngine/Resources/Models/ModelWrapper.h
../../Sources/GameEngine/Resources/Models/WBLoader/AbstractLoader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Binary/BinaryLoader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Binary/BinaryReader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Binary/BinaryWriter.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Collada.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/MergeTool/MergeTool.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Animations/Animation.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Animations/AnimationSampler.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Animations/Channel.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Animations/LibraryAnimations.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/ColladaData.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Common/Accessor.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Common/Array.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Common/Input.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Common/Param.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Common/Source.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Common/TechniqueCommon.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Common/VCount.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Controllers/Controller.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Controllers/Joints.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Controllers/LibraryControllers.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Controllers/Skin.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Controllers/VertexWeights.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Effects/Color.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Effects/Effect.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Effects/Float.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Effects/LibraryEffects.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Effects/NewParam.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Effects/Sampler.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Effects/Surface.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Geometry/Geometry.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Geometry/LibraryGeometries.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Geometry/Mesh.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Geometry/Polylist.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Geometry/Vertices.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Images/Image.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Images/LibraryImages.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Materials/LibraryMaterials.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/Materials/Material.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/VisualScenes/Extra.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/VisualScenes/InstanceController.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/VisualScenes/LibraryVisualScenes.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/VisualScenes/Matrix.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/VisualScenes/Node.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/VisualScenes/Rotate.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/VisualScenes/Scale.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/VisualScenes/Translate.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Types/VisualScenes/VisualScene.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Xml/ColladaCommon.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Xml/GeometryReader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Xml/LibraryAnimationsReader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Xml/LibraryControllersReader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Xml/libraryEffectsReader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Xml/LibraryImagesReader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Xml/LibraryVisualScenesReader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Xml/MainReader.h
../../Sources/GameEngine/Resources/Models/WBLoader/Collada/Xml/MaterialReader.h
../../Sources/GameEngine/Resources/Models/WBLoader/LoaderManager.h
../../Sources/GameEngine/Resources/Models/WBLoader/MeshData.h
../../Sources/GameEngine/Resources/Models/WBLoader/Terrain/TerrainMeshLoader.h
../../Sources/GameEngine/Resources/Models/WBLoader/WaveFront/WaveFrontObj.h
../../Sources/GameEngine/Resources/ResourceManager.h
../../Sources/GameEngine/Resources/ShaderBuffers/PerAppBuffer.h
../../Sources/GameEngine/Resources/ShaderBuffers/PerFrameBuffer.h
../../Sources/GameEngine/Resources/ShaderBuffers/PerInstances.h
../../Sources/GameEngine/Resources/ShaderBuffers/PerMeshObject.h
../../Sources/GameEngine/Resources/ShaderBuffers/PerObjectConstants.h
../../Sources/GameEngine/Resources/ShaderBuffers/PerObjectUpdate.h
../../Sources/GameEngine/Resources/ShaderBuffers/PerPoseUpdate.h
../../Sources/GameEngine/Resources/ShaderBuffers/ShaderBuffersBindLocations.h
../../Sources/GameEngine/Resources/TextureLoader.h
../../Sources/GameEngine/Resources/Textures/CubeMapTexture.h
../../Sources/GameEngine/Resources/Textures/GeneralTexture.h
../../Sources/GameEngine/Resources/Textures/HeightMap.h
../../Sources/GameEngine/Resources/Textures/Image.h
../../Sources/GameEngine/Resources/Textures/MaterialTexture.h
../../Sources/GameEngine/Resources/Textures/Texture.h
../../Sources/GameEngine/Resources/Textures/TextureFlip.h
../../Sources/GameEngine/Scene/SceneDef.h
../../Sources/GameEngine/Scene/SceneEvents.h
../../Sources/GameEngine/Scene/SceneFactoryBase.h
../../Sources/GameEngine/Scene/SceneLoader.h
../../Sources/GameEngine/Scene/SceneManager.h
../../Sources/GameEngine/Scene/SceneReader.h
../../Sources/GameEngine/Scene/SceneWrapper.h
../../Sources/GameEngine/Scene/SceneWriter.h
../../Sources/GameEngine/Shaders/IShaderFactory.h
../../Sources/GameEngine/Shaders/IShaderProgram.h
../../Sources/GameEngine/Shaders/Loading/LoadingShader.h
../../Sources/GameEngine/Shaders/Loading/LoadingShaderUnfiorms.h
../../Sources/GameEngine/Shaders/ShaderFactory.h
../../Sources/GameEngine/Shaders/ShaderProgram.h
../../Sources/GameEngine/Time/DayNightCycle.h
../../Sources/GameEngine/Time/GameTime.h
../../Sources/GameEngine/Time/Time.h
../../Sources/GameEngine/Common/common.hpp
../../Sources/GameEngine/Components/Renderer/Entity/RendererComponent.hpp
../../Sources/GameEngine/Display/DisplayManager.hpp
../../Sources/GameEngine/Renderers/GUI/Texutre/GuiTexture.hpp
../../Sources/GameEngine/Renderers/Objects/Shadows/IShadowFrameBuffer.hpp
../../Sources/GameEngine/Renderers/Objects/Shadows/ShadowMapRenderer.hpp
../../Sources/GameEngine/Resources/IResourceManager.hpp
../../Sources/GameEngine/Scene/Scene.hpp
)
