set(GameEngineTestsIncludes
../../Sources/GameEngineTests/Tests/Mocks/Network/SDLNetWrapperMock.h
../../Sources/GameEngineTests/Tests/Mocks/Camera/CameraMock.h
../../Sources/GameEngineTests/Tests/Mocks/Components/ComponentFactoryMock.h
../../Sources/GameEngineTests/Tests/Mocks/Renderers/FrameBuffer/FrameBufferMock.h
../../Sources/GameEngineTests/Tests/Mocks/Api/GraphicsApiMock.h
../../Sources/GameEngineTests/Tests/Mocks/Physics/PhysicsApiMock.h
../../Sources/GameEngineTests/Tests/Mocks/Shaders/ShaderProgramMock.h
../../Sources/GameEngineTests/Tests/Mocks/Shaders/ShaderFactoryMock.h
../../Sources/GameEngineTests/Tests/Mocks/Resources/TextureLoaderMock.h
../../Sources/GameEngineTests/Tests/Mocks/Resources/ResourcesManagerMock.h
../../Sources/GameEngineTests/Tests/Mocks/Resources/GpuResourceLoaderMock.h
../../Sources/GameEngineTests/Tests/Mocks/Resources/OpenGLLoaderMock.h
../../Sources/GameEngineTests/Tests/Mocks/Resources/ColladaLoaderMock.h
../../Sources/GameEngineTests/Tests/UT/Components/BaseComponent.h
../../Sources/GameEngineTests/Tests/Mocks/Renderers/Objects/Shadows/ShadowFrameBufferMock.hpp
)
