set(GameEngineTestsIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Camera/CameraMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Physics/PhysicsApiMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Resources/ResourcesManagerMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Resources/TextureLoaderMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Resources/GpuResourceLoaderMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Resources/OpenGLLoaderMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Resources/ColladaLoaderMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Renderers/GuiTextFactoryMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Api/GraphicsApiMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Api/FrameBufferMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Api/InputManagerMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/UT/Components/BaseComponent.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Renderers/Objects/Shadows/ShadowFrameBufferMock.hpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/GameEngineTests/Tests/Mocks/Api/WindowApiMock.hpp
)
