set(GraphicsApiIncludes
../../Sources/GraphicsApi/ShaderQuaility.h
../../Sources/GraphicsApi/Image.h
../../Sources/GraphicsApi/GraphicsObject.h
../../Sources/GraphicsApi/ShaderBufferVariable.h
../../Sources/GraphicsApi/BufferParamters.h
../../Sources/GraphicsApi/BlendFunctionsTypes.h
../../Sources/GraphicsApi/IGraphicsApi.h
../../Sources/GraphicsApi/TextureInfo.h
../../Sources/GraphicsApi/RenderType.h
../../Sources/GraphicsApi/VariableType.h
../../Sources/GraphicsApi/MeshRawData.h
../../Sources/GraphicsApi/ShaderTypes.h
../../Sources/GraphicsApi/RendererType.h
../../Sources/GraphicsApi/ShaderFiles.h
../../Sources/GraphicsApi/Surface.h
../../Sources/GraphicsApi/FunctionsTypes.h
../../Sources/GraphicsApi/TextureParamters.h
../../Sources/GraphicsApi/ApiMessages.h
../../Sources/GraphicsApi/IFrameBuffer.h
../../Sources/GraphicsApi/LineMesh.h
../../Sources/GraphicsApi/TextureTarget.h
../../Sources/GraphicsApi/ImageFilters.h
../../Sources/GraphicsApi/WindowType.h
../../Sources/GraphicsApi/GraphicsApiDef.h
../../Sources/GraphicsApi/ShaderProgramType.h
../../Sources/GraphicsApi/WindowApi.hpp
)
