set(GraphicsApiIncludes
../../Sources/GraphicsApi/ShaderFiles.h
../../Sources/GraphicsApi/ShaderBufferVariable.h
../../Sources/GraphicsApi/ApiMessages.h
../../Sources/GraphicsApi/TextureParamters.h
../../Sources/GraphicsApi/MeshRawData.h
../../Sources/GraphicsApi/BufferParamters.h
../../Sources/GraphicsApi/ShadersTypes.h
../../Sources/GraphicsApi/BlendFunctionsTypes.h
../../Sources/GraphicsApi/WindowType.h
../../Sources/GraphicsApi/RenderType.h
../../Sources/GraphicsApi/ShaderTypes.h
../../Sources/GraphicsApi/Surface.h
../../Sources/GraphicsApi/FunctionsTypes.h
../../Sources/GraphicsApi/TextureTarget.h
../../Sources/GraphicsApi/IGraphicsApi.h
../../Sources/GraphicsApi/VariableType.h
../../Sources/GraphicsApi/ShaderQuaility.h
../../Sources/GraphicsApi/WindowApi.hpp
)
