set(GwintServerIncludes
../../Sources/GwintServer/Network/User.h
../../Sources/GwintServer/Network/SDLServerGetway.h
../../Sources/GwintServer/Messages/Message.h
../../Sources/GwintServer/Messages/SwapCardMessage.h
../../Sources/GwintServer/Messages/MessageParser.h
../../Sources/GwintServer/Messages/PushCardMessage.h
../../Sources/GwintServer/Messages/Header.h
../../Sources/GwintServer/Messages/Body.h
../../Sources/GwintServer/GameServer.h
../../Sources/GwintServer/Dispatcher.h
)
