set(GwintIncludes
../../Sources/Gwint/Gwint.h
../../Sources/Gwint/States/PlayerMoveState.h
../../Sources/Gwint/States/ChooseCardState.h
../../Sources/Gwint/States/EnemyState.h
../../Sources/Gwint/States/EnemyMockState.h
../../Sources/Gwint/States/State.h
../../Sources/Gwint/Network/NetworkStates.h
../../Sources/Gwint/Network/NetworkUtils.h
../../Sources/Gwint/Network/SDLClientGetway.h
../../Sources/Gwint/Renderer.h
../../Sources/Gwint/Cards/Card.h
../../Sources/Gwint/Cards/GameCards.h
../../Sources/Gwint/Cards/CardReader.h
../../Sources/Gwint/Messages/Messages.h
../../Sources/Gwint/GameLine.h
../../Sources/Gwint/GameScene.h
../../Sources/Gwint/Player.h
)
