set(OpenGLApiIncludes
../../Sources/OpenGLApi/SimpleModels/Quad.h
../../Sources/OpenGLApi/Shaders/OpenGLShaderProgram.h
../../Sources/OpenGLApi/Shaders/ShaderManager.h
../../Sources/OpenGLApi/Shaders/SimpleForwardShaderFiles.h
../../Sources/OpenGLApi/Shaders/SimpleDeprecetedShaders.h
../../Sources/OpenGLApi/Shaders/FullDefferedShaderFiles.h
../../Sources/OpenGLApi/OpenGLUtils.h
../../Sources/OpenGLApi/SDL2/SDLOpenGL.h
../../Sources/OpenGLApi/SDL2/SdlKeyConverter.h
../../Sources/OpenGLApi/SDL2/InputSDL.h
../../Sources/OpenGLApi/GlFrameBuffer.h
../../Sources/OpenGLApi/Font.h
../../Sources/OpenGLApi/OpenGLMesh.h
../../Sources/OpenGLApi/IdPool.h
../../Sources/OpenGLApi/OpenGLApi.h
)
