set(OpenGLApiIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/Font.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/GlFrameBuffer.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/IdPool.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/OpenGLApi.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/OpenGLMesh.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/OpenGLUtils.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/SDL2/InputSDL.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/SDL2/SDLOpenGL.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/SDL2/SdlKeyConverter.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/Shaders/FullDefferedShaderFiles.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/Shaders/OpenGLShaderProgram.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/Shaders/ShaderManager.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/Shaders/SimpleDeprecetedShaders.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/Shaders/SimpleForwardShaderFiles.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/OpenGLApi/SimpleModels/Quad.h
)
