set(RpgGameServerIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/AbstractUser.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Hero/Classes/Knight.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Hero/CharacetrContext.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Hero/BaseHero.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/SelectCharacter/SelectCharacterHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/Distribute/DistributeHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/GetCharacters/GetCharactersHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/CharacterController/CharacterControllerHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Handlers/GetCharactersData/GetCharactersDataHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Manager.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/User.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Context.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Scenarios/ScenariosTypes.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Scenarios/CharacterSelect/CharacterSelect.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Scenarios/IScenario.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Database/DatabaseTransformInfo.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Database/DatabaseWrapperMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Database/User.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Database/IDatabaseWrapper.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Database/LocalDatabase.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/GameServer.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/ControllerCreator.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Map.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/RpgGameServer/GameServer/Hero/HeroFactory.hpp
)
