set(TestGameIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/GuiEdytorScene.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/MessageProccesing/Dispatcher.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/mrpg_main.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/PlayerMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/GetCharacter/GetCharactersHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/DisconnectCharacter/DisconnectHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/GetCharacterData/GetCharacterDataHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/Transform/TransformHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Handlers/SelectCharacter/SelectCharacterHandler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/MrpgGameContext.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/MainScene/MainRpgScene.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/SelectingCharacterState.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/ISelectState.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/WaitForConfirmationState.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/GetCharacterState.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/CharacterSlot.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/SelectCharacter/SelectCharacterScene.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/Login/Login.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/MRpgScene.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Scenes/ScenesFactory.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Characters/NetworkCharacter.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Characters/ModelsCreator.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Characters/PlayerController.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/MRpg/Characters/NetworkCharacterManger.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Physics/PhyscisTestScene.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Physics/Scenes/PhysicsScene.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Physics/Scenes/PhysicsSceneFactory.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Single/PlayerInputController.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Single/SingleStart.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Single/Scene/MainScene.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/Single/Scene/TestSceneFactory.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/TestGame/CharacterStats.h
)
