set(TestGameIncludes
../../Sources/TestGame/CharacterStats.h
../../Sources/TestGame/GuiEdytorScene.h
../../Sources/TestGame/MRpg/Characters/ModelsCreator.h
../../Sources/TestGame/MRpg/Characters/NetworkCharacter.h
../../Sources/TestGame/MRpg/Characters/NetworkCharacterManger.h
../../Sources/TestGame/MRpg/Characters/PlayerController.h
../../Sources/TestGame/MRpg/Handlers/DisconnectCharacter/DisconnectHandler.h
../../Sources/TestGame/MRpg/Handlers/GetCharacter/GetCharactersHandler.h
../../Sources/TestGame/MRpg/Handlers/GetCharacterData/GetCharacterDataHandler.h
../../Sources/TestGame/MRpg/Handlers/SelectCharacter/SelectCharacterHandler.h
../../Sources/TestGame/MRpg/Handlers/Transform/TransformHandler.h
../../Sources/TestGame/MRpg/MessageProccesing/Dispatcher.h
../../Sources/TestGame/MRpg/MrpgGameContext.h
../../Sources/TestGame/MRpg/mrpg_main.h
../../Sources/TestGame/MRpg/PlayerMock.h
../../Sources/TestGame/MRpg/Scenes/Login/Login.h
../../Sources/TestGame/MRpg/Scenes/MainScene/MainRpgScene.h
../../Sources/TestGame/MRpg/Scenes/MRpgScene.h
../../Sources/TestGame/MRpg/Scenes/ScenesFactory.h
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/CharacterSlot.h
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/SelectCharacterScene.h
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/GetCharacterState.h
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/ISelectState.h
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/SelectingCharacterState.h
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/States/WaitForConfirmationState.h
../../Sources/TestGame/Player.h
../../Sources/TestGame/Single/PlayerInputController.h
../../Sources/TestGame/Single/Scene/MainScene.h
../../Sources/TestGame/Single/Scene/TestSceneFactory.h
../../Sources/TestGame/Single/SingleStart.h
)
