set(TestGameIncludes
../../Sources/TestGame/CharacterStats.h
../../Sources/TestGame/GuiEdytorScene.h
../../Sources/TestGame/MainScene.h
../../Sources/TestGame/MRpg/Characters/NetworkCharacter.h
../../Sources/TestGame/MRpg/Characters/PlayerController.h
../../Sources/TestGame/MRpg/MessageProccesing/Dispatcher.h
../../Sources/TestGame/MRpg/MrpgGameContext.h
../../Sources/TestGame/MRpg/mrpg_main.h
../../Sources/TestGame/MRpg/Scenes/Login.h
../../Sources/TestGame/MRpg/Scenes/MainScene/MainRpgScene.h
../../Sources/TestGame/MRpg/Scenes/ScenesFactory.h
../../Sources/TestGame/MRpg/Scenes/SelectCharacter/SelectCharacterScene.h
../../Sources/TestGame/Player.h
)
