set(TestsIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Camera/CameraMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Resources/ResourceManagerFactoryMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Resources/TextureLoaderMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Resources/ResourcesManagerMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Resources/GpuResourceLoaderMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Resources/OpenGLLoaderMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Resources/ModelLoaderFactoryMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Resources/ColladaLoaderMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Physics/PhysicsApiMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Renderers/GuiTextFactoryMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Renderers/RendererFactoryMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/MockThreadSync.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Api/InputManagerMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Api/GraphicsApiMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Api/FrameBufferMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Scene/SceneManagerMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Scene/SceneFactoryMock.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/UT/EngineBasedTest.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/UT/Components/CharacterController/CharacterControllerTests.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/UT/Components/Animations/AnimationStateFixture.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/UT/Components/BaseComponent.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Renderers/Objects/Shadows/ShadowFrameBufferMock.hpp
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/Tests/Mocks/Api/WindowApiMock.hpp
)
