set(UtilsNetworkIncludes
../../Sources/UtilsNetwork/MessageTarget.h
../../Sources/UtilsNetwork/ConnectionManager.h
../../Sources/UtilsNetwork/IMessage.h
../../Sources/UtilsNetwork/MessageFormat.h
../../Sources/UtilsNetwork/SDLNetWrapper.h
../../Sources/UtilsNetwork/Reciever.h
../../Sources/UtilsNetwork/Sender.h
../../Sources/UtilsNetwork/ClientCreator.h
../../Sources/UtilsNetwork/ISDLNetWrapper.h
../../Sources/UtilsNetwork/Messages/BinaryConnectionMessageConverter.h
../../Sources/UtilsNetwork/Messages/XmlConnectionMessageConverter.h
../../Sources/UtilsNetwork/Messages/MessageTypes.h
../../Sources/UtilsNetwork/Messages/TextMessage.h
../../Sources/UtilsNetwork/Messages/Connection/ConnectionMessage.h
../../Sources/UtilsNetwork/Messages/Connection/ConnectionStatus.h
../../Sources/UtilsNetwork/Messages/Connection/AuthenticationMessage.h
../../Sources/UtilsNetwork/NetworkUtils.h
../../Sources/UtilsNetwork/NetworkCreator.h
../../Sources/UtilsNetwork/UserAccount.h
../../Sources/UtilsNetwork/User.h
../../Sources/UtilsNetwork/ServerCreator.h
../../Sources/UtilsNetwork/ConectContext.h
../../Sources/UtilsNetwork/Gateway.h
../../Sources/UtilsNetwork/NetworkTypes.h
../../Sources/UtilsNetwork/IMessageConverter.h
)
