set(UtilsNetworkIncludes
../../Sources/UtilsNetwork/Messages/CreateCharacter/CreateCharacterMsgResp.h
../../Sources/UtilsNetwork/Messages/CreateCharacter/CreateCharacterMsgReq.h
../../Sources/UtilsNetwork/Messages/SelectCharacter/SelectCharacterMsgResp.h
../../Sources/UtilsNetwork/Messages/SelectCharacter/SelectCharacterMsgReq.h
../../Sources/UtilsNetwork/Messages/MessageTypes.h
../../Sources/UtilsNetwork/Messages/IMessage.h
../../Sources/UtilsNetwork/Messages/MessageStatus.h
../../Sources/UtilsNetwork/Messages/Conntection/AuthenticationMessage.h
../../Sources/UtilsNetwork/Messages/Conntection/ConnectionStatus.h
../../Sources/UtilsNetwork/Messages/Conntection/ConnectionMessage.h
../../Sources/UtilsNetwork/Messages/TransformMessages/TransformMessageTypes.h
../../Sources/UtilsNetwork/Messages/TransformMessages/TransformMsgReq.h
../../Sources/UtilsNetwork/Messages/TransformMessages/TransformMsgResp.h
../../Sources/UtilsNetwork/Messages/PingMessage.h
../../Sources/UtilsNetwork/Messages/MessageTarget.h
../../Sources/UtilsNetwork/Messages/RemoveCharacter/DisconnectCharacterMsg.h
../../Sources/UtilsNetwork/Messages/GetCharacters/GetCharactersMsgReq.h
../../Sources/UtilsNetwork/Messages/GetCharacters/CharacterInfo.h
../../Sources/UtilsNetwork/Messages/GetCharacters/GetCharactersMsgResp.h
../../Sources/UtilsNetwork/Messages/GetCharacterData/GetCharacterDataMsgResp.h
../../Sources/UtilsNetwork/Messages/GetCharacterData/GetCharactersDataMsgReq.h
../../Sources/UtilsNetwork/Messages/GetCharacterData/GetCharacterDataMsgReq.h
../../Sources/UtilsNetwork/User.h
../../Sources/UtilsNetwork/ConectContext.h
../../Sources/UtilsNetwork/Sender.h
../../Sources/UtilsNetwork/BoxesGateway.h
../../Sources/UtilsNetwork/ISDLNetWrapper.h
../../Sources/UtilsNetwork/ClientCreator.h
../../Sources/UtilsNetwork/Reciever.h
../../Sources/UtilsNetwork/ServerCreator.h
../../Sources/UtilsNetwork/NetworkCreator.h
../../Sources/UtilsNetwork/NetworkUtils.h
../../Sources/UtilsNetwork/ConnectionManager.h
../../Sources/UtilsNetwork/NetworkTypes.h
../../Sources/UtilsNetwork/SDLNetWrapper.h
../../Sources/UtilsNetwork/UserAccount.h
../../Sources/UtilsNetwork/Gateway.h
)
