set(WindowAppCreatorIncludes
../../Sources/WindowAppCreator/Items/Actions.h
../../Sources/WindowAppCreator/Items/Button.h
../../Sources/WindowAppCreator/Items/IItemBuidler.h
../../Sources/WindowAppCreator/Items/Item.h
../../Sources/WindowAppCreator/Items/ItemMessages.h
../../Sources/WindowAppCreator/Items/ItemsGroup.h
../../Sources/WindowAppCreator/Items/Layout.h
../../Sources/WindowAppCreator/Items/Rect.h
../../Sources/WindowAppCreator/Items/Window.h
../../Sources/WindowAppCreator/Items/windows/Button/Win32_Button.h
../../Sources/WindowAppCreator/Items/windows/Window/Win32_Window.h
../../Sources/WindowAppCreator/Items/windows/WindowsItem.h
../../Sources/WindowAppCreator/Items/windows/WindowsItemsBuilder.h
../../Sources/WindowAppCreator/WindowAppCreator.h
)
