set(WindowAppCreatorIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/Actions.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/Layout.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/IItemBuidler.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/windows/WindowsItemsBuilder.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/windows/Window/Win32_Window.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/windows/WindowsItem.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/windows/Button/Win32_Button.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/Rect.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/Item.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/ItemMessages.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/Window.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/Button.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/Items/ItemsGroup.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WindowAppCreator/WindowAppCreator.h
)
