set(WxEditorIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/SceneTreeView/SceneTreeCtrl.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/SceneTreeView/DisableHelper.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/MaterialEditor/MaterialEditorFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EngineRelated/WxKeyEventType.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EngineRelated/NewScene.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EngineRelated/EmptyScene.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EngineRelated/WxInputManager.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EngineRelated/WxOpenGLApiWrapper.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EngineRelated/GLCanvas.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EngineRelated/WxWindowApi.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EngineRelated/WxScenesDef.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EngineRelated/WxEditorSceneFactory.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TerrainTool/TerrainToolPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TerrainTool/TextureButton.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TerrainTool/TerrainSelectionDialog.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TerrainTool/TexturePickerPopup.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/OptionsFrame/Theme.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/OptionsFrame/OptionsFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/StartupDialog/StartupDialog.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/StartupDialog/ProjectsCMakeTemplate.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TreeGeneration/TreeGenerationParams.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TreeGeneration/TreeGeneration.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxHelpers/LoadingDialog.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxHelpers/EditorUitls.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxHelpers/WxClientData.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxHelpers/FileDropTarget.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxHelpers/ThumbnailCache.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ControlsIds.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ProjectPanel/model3d_icon.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ProjectPanel/ProjectPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/App.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/TransformCommand.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/Command.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/PlantPainterCommand.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/HeightPainterCommand.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/UndoManager.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/MultipleHeightPainterCommand.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/TextureCommandData.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/RemoveObjectCommand.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/MultipleBlendmapPainterCommand.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/AddObjectCommand.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Commands/TextureCommandEntry.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/ComponentPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/ComponentPickerPopup.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/TransformPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/BuildProcess.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/BuildComponentLogFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/ReloadComponentLibEvent.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/MainFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/AnimationViewer/AnimationFileDropTarget.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/AnimationViewer/AnimationViwerIcon.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/AnimationViewer/AnimationViewerFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ProjectManager.h
)
