set(WxEditorIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TreeHelper.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Theme.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ThumbnailCache.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/App.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TransformPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxWindowApi.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxInputManager.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/OptionsFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/MainFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ProjectPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxOpenGLApiWrapper.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/GLCanvas.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxKeyEventType.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPickerPopup.h
)
