set(WxEditorIncludes
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxHelpers/WxClientData.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxHelpers/FileDropTarget.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ProjectsCMakeTemplate.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxOpenGLApiWrapper.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/DisableHelper.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/EditorUitls.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/MaterialEditorFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ProjectManager.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/ComponentPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/ReloadComponentLibEvent.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/ComponentPickerPopup.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ComponentPanel/TransformPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ProjectPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TerrainTool/TextureButton.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TerrainTool/TexturePickerPopup.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TerrainTool/TerrainToolPanel.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/TerrainTool/TerrainSelectionDialog.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxKeyEventType.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ThumbnailCache.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/AnimationViewer/AnimationViwerIcon.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/AnimationViewer/AnimationFileDropTarget.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/AnimationViewer/AnimationViewerFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/App.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/LoadingDialog.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/StartupDialog.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/model3d_icon.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxInputManager.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/SceneTreeCtrl.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/BuildLogFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/WxWindowApi.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/MainFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/ControlsIds.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/OptionsFrame.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/GLCanvas.h
${CMAKE_CURRENT_SOURCE_DIR}/../../Sources/WxEditor/Theme.h
)
