if(BUILD_GAME_ENGINE OR BUILD_TEST_GAME)
    include(./Sources/GraphicsApiSources.cmake)
    add_library(GraphicsApiLib ${GraphicsApiSources})
    if(BUILD_I386)
        set_target_properties(GraphicsApiLib PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
    endif()
endif()