if(BUILD_GAME_ENGINE OR BUILD_TEST_GAME)
    include(./Sources/InputSources.cmake)
    add_library(InputLib ${InputSources})
    if(BUILD_I386)
        set_target_properties(InputLib PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
    endif()
endif()