if(BUILD_TERRAIN_GENERATOR)
    include(./Sources/TerrainGeneratorSources.cmake)
    add_executable(TerrainGeneratorExe ${TerrainGeneratorSources})
    target_link_libraries(TerrainGeneratorExe LibNoise pthread)
endif()