#pragma once

enum GuiEditorControlIds
{
    ID_RECENT_FIRST = 3000,
    ID_RECENT_LAST = 3010,
    ID_UNDO = 3011,
    ID_REDO,
    ID_REOPEN,
    ID_ADD_WINDOW,
    ID_ADD_TEXT,
    ID_ADD_MULTI_LINE_TEXT,
    ID_ADD_TEXTURE,
    ID_ADD_BUTTON,
    ID_ADD_V_LAYOUT,
    ID_ADD_H_LAYOUT
};
