set(GameEngineSources
../GameEngine/Scene/SceneLoader.cpp
../GameEngine/Scene/Scene.cpp
../GameEngine/Display/DisplayManager.cpp
../GameEngine/Objects/Transform.cpp
../GameEngine/Objects/ObjectBuilder.cpp
../GameEngine/Objects/GameObject.cpp
../GameEngine/Objects/RenderAble/Terrain/TerrainWrapper.cpp
../GameEngine/Objects/RenderAble/Terrain/TerrainCreateUtils.cpp
../GameEngine/Objects/RenderAble/Terrain/Terrain.cpp
../GameEngine/Objects/RenderAble/Entity/EntityWrapper.cpp
../GameEngine/Objects/RenderAble/Entity/Entity.cpp
../GameEngine/Resources/Textures/CubeMapTexture.cpp
../GameEngine/Resources/Textures/Texture.cpp
../GameEngine/Resources/Textures/MaterialTexture.cpp
../GameEngine/Resources/TextureLoader.cpp
../GameEngine/Resources/ResourceManager.cpp
../GameEngine/Resources/Models/Assimp/AssimpModel.cpp
../GameEngine/Resources/Models/Bone.cpp
../GameEngine/Resources/Models/Model.cpp
../GameEngine/Resources/Models/Mesh.cpp
../GameEngine/Resources/Models/WBLoader/Collada/ColladaDae.cpp
../GameEngine/Resources/Models/WBLoader/MeshData.cpp
../GameEngine/Resources/Models/WBLoader/WaveFront/WaveFrontObj.cpp
../GameEngine/Resources/Models/WBLoader/MyModel.cpp
../GameEngine/Resources/OpenGLLoader.cpp
../GameEngine/Input/InputManager.cpp
../GameEngine/Input/Input.cpp
../GameEngine/Lights/Light.cpp
../GameEngine/Engine/Engine.cpp
../GameEngine/Engine/Projection.cpp
../GameEngine/Engine/Configuration.cpp
../GameEngine/Engine/Debuger.cpp
../GameEngine/Shaders/Deffered/LightPassShader.cpp
../GameEngine/Shaders/ShaderProgram.cpp
../GameEngine/Shaders/Loading/LoadingShader.cpp
../GameEngine/Time/DayNightCycle.cpp
../GameEngine/Time/GameTime.cpp
../GameEngine/Renderers/FullRenderer.cpp
../GameEngine/Renderers/Terrain/Classic/TerrainRenderer.cpp
../GameEngine/Renderers/Terrain/Classic/Shaders/TerrainShader.cpp
../GameEngine/Renderers/Terrain/Tesselation/TessellationTerrainRenderer.cpp
../GameEngine/Renderers/Terrain/Tesselation/Shaders/TesselationTerrainShader.cpp
../GameEngine/Renderers/GUI/Text/FontShader.cpp
../GameEngine/Renderers/GUI/Text/Font.cpp
../GameEngine/Renderers/GUI/GuiRenderer.cpp
../GameEngine/Renderers/GUI/GuiElement.cpp
../GameEngine/Renderers/LightPassRenderer.cpp
../GameEngine/Renderers/SimpleRenderer.cpp
../GameEngine/Renderers/Renderer.cpp
../GameEngine/Renderers/Framebuffer/FrameBuffer.cpp
../GameEngine/Renderers/Framebuffer/DeferedFrameBuffer/DeferedFrameBuffer.cpp
../GameEngine/Renderers/Entity/EntityRenderer.cpp
../GameEngine/Renderers/Entity/Shaders/EntityShader.cpp
../GameEngine/Renderers/Entity/Shaders/SimpleEnityShader.cpp
../GameEngine/Renderers/Entity/Shaders/GeometryEntityShader.cpp
../GameEngine/Renderers/SkyBox/Shaders/SkyBoxShader.cpp
../GameEngine/Renderers/SkyBox/SkyBoxRenderer.cpp
../GameEngine/Renderers/LodingScreenRenderer.cpp
../GameEngine/Renderers/Grass/GrassRenderer.cpp
../GameEngine/Renderers/Grass/Shaders/GrassShader.cpp
../GameEngine/Camera/FirstPersonCamera.cpp
../GameEngine/Camera/Camera.cpp
../GameEngine/Camera/Frustrum.cpp
../GameEngine/Camera/ThridPersonCamera.cpp
../GameEngine/Api/SDL2/SDLOpenGL.cpp
../GameEngine/Api/SDL2/InputSDL.cpp
)
